[functions]
  external_node_modules = ["express", "ejs", "body-parser", "ent", "express-session"]
  included_files = ["views/*.*"]
  node_bundler = "esbuild"
  directory = "functions/"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/app/*"
